import {useEffect,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Users,History} from 'lucide-react';
import {api,amount,compact} from '../../lib/api';

export const TokenActivity=({project:p,simulation})=>{
 const [tab,setTab]=useState('trades'),[trades,setTrades]=useState([]),[holders,setHolders]=useState([]),[error,setError]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);Promise.all([api.get(`/market/${p.id}/trades`),api.get(`/market/${p.id}/holders`)]).then(([t,h])=>{if(active){setTrades(t.data.items);setHolders(h.data.items);setError(false);}}).catch(()=>active&&setError(true)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[p.id,retry,simulation?.version,simulation?.id]);
 const mine=(simulation?.trades||[]).filter(t=>t.project_id===p.id).map(t=>({...t,trader:'You (demo)',mine:true}));
 const mineIds=new Set(mine.map(t=>t.id));const rows=tab==='mine'?mine:[...mine,...trades.filter(t=>!mineIds.has(t.id))].sort((a,b)=>b.executed_at.localeCompare(a.executed_at)).slice(0,24);
 return <section className="token-activity" data-testid="token-activity"><div className="activity-tabs">{[['trades','Transactions'],['holders',`Holders (${amount(p.holders)})`],['mine','My trades'],['about','About']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'selected':''} data-testid={`activity-tab-${id}`}>{label}{id==='mine'&&mine.length>0&&<small>{mine.length}</small>}</button>)}</div>
  {loading?<div className="activity-empty" data-testid="activity-loading">Loading activity…</div>:error?<div className="activity-empty" data-testid="activity-error">Activity unavailable. <button className="text-link" onClick={()=>setRetry(v=>v+1)} data-testid="activity-retry">Try again</button></div>:tab==='about'?<div className="token-about" data-testid="token-about"><h3>What's in ${p.ticker}?</h3><p>{p.description}</p><dl>{[['Protocol',p.protocol],['Trading pair',`${p.ticker}/SOL`],['Token supply',`${compact(p.supply)} ${p.ticker}`],['Mint address','Not issued · demo token'],['Fill asset',`${p.asset} · not the trading pair`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="token-social-links">{[['website','Website'],['twitter','X / Twitter'],['telegram','Telegram']].filter(([key])=>p[key]).map(([key,label])=><a href={p[key]} key={key} target="_blank" rel="noreferrer" className="text-link" data-testid={`token-social-${key}`}>{label}<ArrowUpRight size={14}/></a>)}</div></div>:tab==='holders'?<div className="activity-table-wrap"><table className="activity-table" data-testid="holders-table"><thead><tr><th>Rank</th><th>Holder</th><th>Supply held</th><th>Amount</th><th>Value</th></tr></thead><tbody>{holders.map(h=><tr key={h.rank} data-testid={`holder-row-${h.rank}`}><td>#{h.rank}</td><td><Users size={12}/> {h.label}</td><td>{h.percentage}%</td><td>{compact(h.quantity)}</td><td>${compact(h.value_usd)}</td></tr>)}</tbody></table>{!holders.length&&<div className="activity-empty" data-testid="holders-empty">The first holder starts with a demo trade.</div>}<p className="activity-note" data-testid="holders-disclosure">{p.is_launched?'Demo positions only. No real wallets or on-chain holders.':'Illustrative holder distribution. These are not real wallet addresses.'}</p></div>:rows.length?<div className="activity-table-wrap"><table className="activity-table" data-testid="transactions-table"><thead><tr><th>Time</th><th>Type</th><th>Amount ({p.ticker})</th><th>Total (SOL)</th><th>Trader</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} className={t.mine?'your-trade':''} data-testid={`transaction-${t.id}`}><td title={new Date(t.executed_at).toLocaleString()}>{new Date(t.executed_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td><td><span className={`trade-type ${t.side}`}>{t.side==='buy'?<ArrowDownLeft size={12}/>:<ArrowUpRight size={12}/>} {t.side.toUpperCase()}</span></td><td>{compact(t.quantity)}</td><td>{amount(t.sol_amount)}</td><td>{t.trader}</td></tr>)}</tbody></table><p className="activity-note">{p.is_launched||tab==='mine'?'Saved demo fills. No real funds or on-chain transactions.':'Sample activity and your simulated fills. Not live on-chain transactions.'}</p></div>:<div className="activity-empty" data-testid="no-personal-trades"><History size={25}/><strong>Your story starts with a trade.</strong><p>Try a simulated buy. Your fills will appear here.</p></div>}
 </section>;
};